### ISSUE TITLE
TypeError: tree.cleanup is not a function

### ISSUE THREAD

**Issue by woshilapin** [broccolijs/broccoli-source#1]
I tried a very basic example (see below) and reach a `TypeError` problem.

This is the file I used

```
var broccoliSource = require('broccoli-source');
var src = new broccoliSource.WatchedDir('src');
```

nothing more (I tried to reduce as much as possible to keep only what was necessary to still have the error).

And the error is the following.

```
TypeError: tree.cleanup is not a function
    at cleanupTree (/<project_path>/node_modules/broccoli/lib/builder.js:156:17)
    at /<project_path>/node_modules/broccoli/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/<project_path>/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/<project_path>/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /<project_path>/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/<project_path>/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)

Build failed
```

_Note_: I've replaced the project's path with `<project_path>`.

I'm running NodeJS v4.1.1 and have the following dependencies.

```
"devDependencies": {
  "broccoli": "^0.16.8",
  "broccoli-source": "^1.1.0"
}
```

**Comment by joliss** [comment]
Hm, I can't reproduce this with the following `Brocfile.js` - it builds fine:

``` js
var broccoliSource = require('broccoli-source');
var src = new broccoliSource.WatchedDir('src');
module.exports = src;
```

Can you dig some more to narrow down the problem?

**Comment by woshilapin** [comment]
Yes, I was digging more into it and it seems that at some point, I broke Broccoli as the whole.  So it's not related to `broccoli-source`.  And then, I saw your comment.  And I understood.  I reduced my file so much that I didn't even have a `module.exports`.  This is what cause the break... Yes, you can blame me.  Anyway, I take the opportunity to thank you for Broccoli (you're one of the main dev, right?) and please excuse me for the noise.

**Comment by MahnazSheikhi** [comment]
hello.
I came to your problem, how do I solve this issue ?

**Comment by woshilapin** [comment]
As explained above, do you have `module.exports` statement in your file?

**Comment by MahnazSheikhi** [comment]
This is the file I used
-------------------------------------- Brocfile.js---------------------
var tree = './app';
var ES6Modules = require('broccoli-es6modules');
var amdFiles = new ES6Modules(tree, {
    format: 'amd',
    bundleOptions: {
        entry: 'app.js',
        name: 'amdApp'
    }

## });

I realized due to the link below : module.exports is the object that's actually returned as the result of a require call. by 
[http://stackoverflow.com/questions/5311334/what-is-the-purpose-of-node-js-module-exports-and-how-do-you-use-it](http://stackoverflow.com/questions/5311334/what-is-the-purpose-of-node-js-module-exports-and-how-do-you-use-it)

but I cleaned all the lines ,The same problem came again.
