### ISSUE TITLE
Incompatibility with Node 11?

### ISSUE THREAD

**Issue by arthur5005** [broccolijs/broccoli-source#14]
I don't like to ignore engine dependencies in my project, just wanted to know if this is intentional for a known reason or just being cautious?
```
"engines": {
    "node": "8.* || 10.* || >= 12.*"
  },
```

**Comment by rwjblue** [comment]
Node 11 itself is unsupported (see the infographic over at https://nodejs.org/en/about/releases/ for more details).

**Comment by stefanpenner** [comment]
As @rwjblue mentioned, node 11 is itself not supported by node. Unfortunately, we do not have the resources to support something that it's own team does not support.


That being said, if you want to bypass `yarn`'s warning here, feel free to use (at your own risk):
```
yarn --ignore-engines
```
